### ISSUE TITLE
zk cookbook update?

### ISSUE THREAD

**Issue by popsikle** [evertrue/exhibitor-cookbook#41]
is there anything blocking bumping the zk cookbook to version 6? I think version 7 has some breaking changes, but afaict 6 looks pretty safe

**Comment by jeffbyrnes** [comment]
@popsikle I maintain both, so I’ll do some testing & see about upgrading things.

I may, in the future, attempt to decouple them from each other. Even though Exhibitor itself directly depends on ZooKeeper (being that it does nothing otherwise), it seems like it would be best to allow an operator to determine the ZooKeeper installation & config using just the `zookeeper` cookbook, rather than attempting to control it via this cookbook.

That may be a fool’s errand, of course, since Exhibitor does configure ZK.

**Comment by jeffbyrnes** [comment]
@popsikle shipped with 3.0.0!

**Comment by popsikle** [comment]
Thank you!!
